# Generated by Django 6.0.7 on 2026-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
