# Generated by Django 6.0.7 on 2026-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_users_address_users_name_users_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
