# Generated by Django 6.0.7 on 2026-08-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
