# Generated by Django 6.0.7 on 2026-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='M@ha', max_length=15),
            preserve_default=False,
        ),
    ]
