# Generated by Django 6.0.7 on 2026-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('Students', models.ManyToManyField(blank=True, related_name='course', to='admin_app.users')),
            ],
        ),
    ]
