# Generated by Django 6.0.7 on 2026-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_address', models.CharField(max_length=150)),
                ('no_of_rooms', models.IntegerField()),
            ],
        ),
    ]
